import type { WorkspaceTemplate } from "./project-foundry-catalog";

/** Granular scenario templates kept separate so the core capability catalog stays readable. */
export const EXTENDED_WORKSPACE_TEMPLATES: WorkspaceTemplate[] = [
  {
    id: "enterprise-ai-adoption", category: "software", projectType: "team",
    name: { zh: "企业 AI 助手落地", en: "Enterprise AI assistant adoption" },
    description: { zh: "从一个部门任务开始，验证 AI 使用价值、权限边界和人工复核机制。", en: "Validate value, access boundaries, and human review through one departmental task." },
    scenario: { zh: "AI 应用落地", en: "AI adoption" }, scale: { zh: "中大型企业", en: "Mid-size & enterprise" },
    title: "企业 AI 助手落地工作区", audience: "希望在客服、销售、运营或知识工作中安全引入 AI 的企业项目团队",
    problem: "试点工具很多，但可用任务、内部知识权限、结果复核和推广标准不清，难以从演示走向稳定使用。",
    constraints: "先选一个低风险高频任务；保留人工确认；按岗位授权知识；定义停用、回滚与人工升级路径。",
    featureIds: ["problem-framing", "validation-experiments", "ai-coach", "knowledge-base", "role-based-workspaces", "privacy-controls", "audit-history", "analytics-observability"],
    keywords: ["企业AI", "知识助手", "Copilot", "人工复核"],
  },
  {
    id: "data-bi-decision", category: "software", projectType: "research",
    name: { zh: "数据分析与经营驾驶舱", en: "Data analytics & operating cockpit" },
    description: { zh: "围绕一个经营问题统一指标口径、证据和决策复盘。", en: "Align metrics, evidence, and decision review around one operating question." },
    scenario: { zh: "数据驱动决策", en: "Data-driven decisions" }, scale: { zh: "成长型至大型企业", en: "Growth to enterprise" },
    title: "经营数据决策工作区", audience: "需要让业务、数据和管理团队围绕同一组经营信号协作的企业",
    problem: "看板很多但指标定义不一致，异常没有责任人，管理会议讨论数字却无法形成可验证的后续行动。",
    constraints: "从一个经营问题和不超过五个指标开始；保留指标定义与数据来源；区分事实、推断和决策。",
    featureIds: ["problem-framing", "knowledge-base", "decision-journal", "decision-support", "role-based-workspaces", "api-integration", "audit-history", "analytics-observability"],
    keywords: ["BI", "经营分析", "指标体系", "数据驾驶舱"],
  },
  {
    id: "security-compliance-program", category: "software", projectType: "team",
    name: { zh: "安全与合规整改项目", en: "Security & compliance program" },
    description: { zh: "管理控制项、整改证据、责任人与审计轨迹，不替代专业审计。", en: "Manage controls, remediation evidence, owners, and audit trails without replacing professional audit." },
    scenario: { zh: "安全治理", en: "Security governance" }, scale: { zh: "中大型企业", en: "Mid-size & enterprise" },
    title: "安全合规整改工作区", audience: "推进等保、ISO、安全评估或客户安全要求整改的跨职能团队",
    problem: "控制要求分散在文档和工单中，整改证据版本混乱，业务、技术和合规团队无法共享真实进度。",
    constraints: "不自动判定合规；每项控制保留负责人、证据与复核人；敏感材料最小权限；沿用正式审计流程。",
    featureIds: ["action-protocol", "role-based-workspaces", "knowledge-base", "privacy-controls", "audit-history", "api-integration", "progress-dashboard", "quality-release"],
    keywords: ["安全", "合规", "等保", "ISO", "整改"],
  },
  {
    id: "sales-pipeline-operations", category: "professional", projectType: "team",
    name: { zh: "销售漏斗与赢单复盘", en: "Sales pipeline & win review" },
    description: { zh: "统一机会标准、下一步行动和输赢复盘，提高销售判断质量。", en: "Align opportunity criteria, next actions, and win-loss review to improve sales judgment." },
    scenario: { zh: "销售运营", en: "Sales operations" }, scale: { zh: "小微至中型团队", en: "Small to mid-size teams" },
    title: "销售漏斗经营工作区", audience: "销售周期较长、需要团队共同推进机会的 B2B 销售与售前团队",
    problem: "机会阶段依赖主观判断，销售会议只汇报状态，关键假设、客户证据和下一步承诺没有被持续验证。",
    constraints: "先统一一个产品线的阶段定义；每个机会只有一个明确下一步；输赢复盘不用于公开归责。",
    featureIds: ["problem-framing", "opportunity-scoring", "decision-journal", "action-protocol", "role-based-workspaces", "reflection-review", "analytics-observability"],
    keywords: ["销售", "CRM", "漏斗", "赢单", "商机"],
  },
  {
    id: "procurement-vendor-management", category: "professional", projectType: "team",
    name: { zh: "采购与供应商管理", en: "Procurement & vendor management" },
    description: { zh: "让需求、比选依据、履约问题和供应商复盘保持可追溯。", en: "Keep requirements, selection rationale, delivery issues, and vendor reviews traceable." },
    scenario: { zh: "采购协同", en: "Procurement collaboration" }, scale: { zh: "中小至大型企业", en: "SMB to enterprise" },
    title: "采购供应商工作区", audience: "需要协调业务需求、采购决策与供应商履约的企业采购和使用部门",
    problem: "需求定义不清、比选证据分散，合同后履约问题无法回到下一次采购标准，形成重复风险。",
    constraints: "不替代招采与法务程序；敏感报价分级访问；每项选择保留标准、证据、复核人与利益冲突声明。",
    featureIds: ["problem-framing", "decision-journal", "decision-support", "role-based-workspaces", "knowledge-base", "privacy-controls", "audit-history"],
    keywords: ["采购", "供应商", "比选", "履约"],
  },
  {
    id: "customer-support-improvement", category: "professional", projectType: "team",
    name: { zh: "客户服务与工单改善", en: "Customer support improvement" },
    description: { zh: "从重复问题、服务恢复和知识沉淀中持续改善客户体验。", en: "Improve customer experience through repeated issues, service recovery, and knowledge capture." },
    scenario: { zh: "客户支持", en: "Customer support" }, scale: { zh: "各规模服务团队", en: "Service teams of any size" },
    title: "客户服务改善工作区", audience: "处理多渠道咨询和售后问题、需要减少重复工单的客户服务团队",
    problem: "一线忙于逐单解决，升级规则和知识不一致，相同问题反复出现却没有进入产品或流程改善。",
    constraints: "先聚焦前三类重复问题；保护客户隐私；明确升级响应时限；质量复盘面向流程而非个体惩罚。",
    featureIds: ["action-protocol", "role-based-workspaces", "knowledge-base", "reflection-review", "privacy-controls", "api-integration", "analytics-observability"],
    keywords: ["客服", "工单", "售后", "知识库", "服务恢复"],
  },
  {
    id: "cross-border-ecommerce", category: "commerce", projectType: "founder",
    name: { zh: "跨境电商单市场验证", en: "Cross-border ecommerce market validation" },
    description: { zh: "用一个市场、一个品类验证本地需求、内容和履约假设。", en: "Validate local demand, content, and fulfillment in one market and category." },
    scenario: { zh: "跨境增长", en: "Cross-border growth" }, scale: { zh: "小微至成长型品牌", en: "Small to growth brands" },
    title: "跨境电商验证工作区", audience: "准备进入一个新国家或平台市场的品牌和跨境运营团队",
    problem: "团队同时扩市场、扩渠道和扩 SKU，本地需求、获客成本、退货原因与履约风险尚未被单独验证。",
    constraints: "一个市场、一个渠道、一个主力品类；遵循当地税务与消费者规则；先定义退出和停止补货门槛。",
    featureIds: ["problem-framing", "opportunity-scoring", "validation-experiments", "asset-pipeline", "decision-journal", "api-integration", "analytics-observability", "quality-release"],
    keywords: ["跨境电商", "出海", "本地化", "履约"],
  },
  {
    id: "live-commerce-operations", category: "commerce", projectType: "creator",
    name: { zh: "直播电商运营", en: "Live commerce operations" },
    description: { zh: "连接选品、内容排期、直播执行和转化复盘。", en: "Connect product selection, content planning, live execution, and conversion review." },
    scenario: { zh: "内容交易", en: "Content commerce" }, scale: { zh: "小型至中型团队", en: "Small to mid-size teams" },
    title: "直播电商运营工作区", audience: "需要稳定直播节奏并提升选品与内容匹配度的品牌或直播团队",
    problem: "选品、脚本和投放各自优化，团队只看成交结果，无法识别内容、商品和人群组合为何有效。",
    constraints: "先维护一个直播间和一个核心人群；每场只验证一个主要假设；不使用误导性宣传或虚假紧迫感。",
    featureIds: ["opportunity-scoring", "validation-experiments", "asset-pipeline", "action-protocol", "reflection-review", "role-based-workspaces", "analytics-observability"],
    keywords: ["直播", "选品", "内容电商", "转化"],
  },
  {
    id: "subscription-retail", category: "commerce", projectType: "founder",
    name: { zh: "订阅制零售与会员复购", en: "Subscription retail & retention" },
    description: { zh: "验证订阅价值、首月体验、留存原因和可持续交付成本。", en: "Validate subscription value, first-month experience, retention, and sustainable delivery cost." },
    scenario: { zh: "会员订阅", en: "Membership subscription" }, scale: { zh: "小微至成长型业务", en: "Small to growth businesses" },
    title: "订阅零售工作区", audience: "经营周期购、会员盒子或高频消费品订阅服务的品牌团队",
    problem: "团队重视首次转化，却不清楚用户持续订阅的真实价值、流失节点和履约成本是否可持续。",
    constraints: "先验证一个订阅周期和一个套餐；透明说明取消规则；跟踪激活、第二期留存与服务成本。",
    featureIds: ["problem-framing", "validation-experiments", "onboarding-loop", "membership-billing", "reflection-review", "privacy-controls", "analytics-observability"],
    keywords: ["订阅", "会员", "复购", "留存"],
  },
  {
    id: "warehouse-operations", category: "industry", projectType: "team",
    name: { zh: "仓储现场与库存异常", en: "Warehouse & inventory exceptions" },
    description: { zh: "围绕收货、拣选、盘点和异常处置建立班组闭环。", en: "Build a team loop around receiving, picking, counting, and exception handling." },
    scenario: { zh: "仓储运营", en: "Warehouse operations" }, scale: { zh: "单仓至多仓", en: "Single to multi-site" },
    title: "仓储运营改善工作区", audience: "需要降低错发、库存差异和异常处理时间的仓储及供应链团队",
    problem: "异常靠即时沟通处理，原因和纠正行动没有持续记录，库存差异与现场等待反复发生。",
    constraints: "先选一个仓和一个高频异常；不替代 WMS；移动端最少输入；每周复盘根因与纠正措施。",
    featureIds: ["action-protocol", "habit-practice", "role-based-workspaces", "reflection-review", "api-integration", "audit-history", "offline-localization", "analytics-observability"],
    keywords: ["仓储", "库存", "WMS", "拣选", "盘点"],
  },
  {
    id: "quality-capa", category: "industry", projectType: "team",
    name: { zh: "质量问题与 CAPA 改善", en: "Quality issues & CAPA" },
    description: { zh: "追踪质量事件、根因、纠正预防措施和验证结果。", en: "Track quality events, root causes, corrective actions, and effectiveness checks." },
    scenario: { zh: "质量管理", en: "Quality management" }, scale: { zh: "制造与受监管企业", en: "Manufacturing & regulated" },
    title: "质量 CAPA 工作区", audience: "需要跨生产、质量、研发和供应商解决重复质量问题的团队",
    problem: "问题关闭等于填完表单，根因证据、措施负责人和有效性验证不连贯，导致同类问题再次发生。",
    constraints: "不替代正式 QMS；遵循既有审批与变更控制；每项关闭必须有证据、复核人和有效性日期。",
    featureIds: ["problem-framing", "action-protocol", "decision-journal", "role-based-workspaces", "knowledge-base", "audit-history", "analytics-observability", "quality-release"],
    keywords: ["质量", "CAPA", "根因", "纠正预防"],
  },
  {
    id: "field-maintenance", category: "industry", projectType: "team",
    name: { zh: "设备巡检与现场维护", en: "Field inspection & maintenance" },
    description: { zh: "为巡检、故障处置、交接和预防性维护建立现场工作区。", en: "Create a field workspace for inspection, faults, handoffs, and preventive maintenance." },
    scenario: { zh: "设备运维", en: "Asset maintenance" }, scale: { zh: "多设备或多站点", en: "Multi-asset or multi-site" },
    title: "现场设备维护工作区", audience: "负责工厂设备、能源设施、楼宇系统或分布式资产的运维团队",
    problem: "巡检记录与故障处理分离，维修经验停留在个人手中，团队难以提前识别重复故障和维护风险。",
    constraints: "不替代法定安全检查；离线可用；重大风险立即走现有应急流程；先覆盖一类关键设备。",
    featureIds: ["action-protocol", "habit-practice", "role-based-workspaces", "knowledge-base", "audit-history", "offline-localization", "analytics-observability"],
    keywords: ["巡检", "设备", "维护", "运维", "现场"],
  },
  {
    id: "corporate-learning", category: "education", projectType: "learning",
    name: { zh: "企业学习与岗位能力", en: "Corporate learning & role capability" },
    description: { zh: "把岗位能力要求转成练习、反馈和业务场景中的可见行为。", en: "Turn role capabilities into practice, feedback, and observable workplace behavior." },
    scenario: { zh: "企业培训", en: "Corporate learning" }, scale: { zh: "中大型组织", en: "Mid-size & enterprise" },
    title: "企业岗位学习工作区", audience: "希望培训真正转化为岗位行为的学习发展、业务经理和员工",
    problem: "课程完成率很高，但学习目标与真实任务脱节，经理反馈和应用证据缺失，无法判断能力是否形成。",
    constraints: "先选一个岗位和一个关键能力；不用于简单绩效排名；只采集学习和业务应用所需证据。",
    featureIds: ["problem-framing", "learning-studio", "habit-practice", "role-based-workspaces", "reflection-review", "progress-dashboard", "privacy-controls", "analytics-observability"],
    keywords: ["企业培训", "L&D", "岗位能力", "学习转化"],
  },
  {
    id: "vocational-apprenticeship", category: "education", projectType: "learning",
    name: { zh: "职业技能与学徒培养", en: "Vocational skills & apprenticeship" },
    description: { zh: "围绕真实工作任务组织示范、练习、反馈与技能认证证据。", en: "Organize demonstration, practice, feedback, and evidence around real work tasks." },
    scenario: { zh: "职业教育", en: "Vocational education" }, scale: { zh: "班组至培训机构", en: "Teams to institutions" },
    title: "职业技能培养工作区", audience: "培养技术工人、服务人员或现场岗位新人的企业和职业教育机构",
    problem: "学员知道理论却无法稳定完成真实任务，师傅反馈随意，技能进展和安全边界没有一致标准。",
    constraints: "以真实岗位标准为准；高风险操作必须现场监督；每项能力包含示范、练习、反馈和复核。",
    featureIds: ["onboarding-loop", "learning-studio", "habit-practice", "role-based-workspaces", "knowledge-base", "reflection-review", "progress-dashboard"],
    keywords: ["职业教育", "学徒", "技能", "实训"],
  },
  {
    id: "expert-knowledge-product", category: "education", projectType: "creator",
    name: { zh: "专家知识产品验证", en: "Expert knowledge product validation" },
    description: { zh: "在大规模制作前，用小型交付验证知识是否解决真实问题。", en: "Validate whether expertise solves a real problem before large-scale production." },
    scenario: { zh: "知识产品", en: "Knowledge products" }, scale: { zh: "个人专家至小团队", en: "Experts to small teams" },
    title: "专家知识产品工作区", audience: "希望把专业经验转为课程、训练营、报告或工具包的专家团队",
    problem: "专家容易从内容目录开始，尚未验证用户愿意为什么结果付费、需要何种练习和支持才能完成改变。",
    constraints: "先完成一轮 10–30 人试点；只承诺一个学习结果；收集行为证据而不仅是满意度。",
    featureIds: ["problem-framing", "validation-experiments", "learning-studio", "asset-pipeline", "reflection-review", "membership-billing", "analytics-observability"],
    keywords: ["知识付费", "专家", "训练营", "课程验证"],
  },
  {
    id: "creator-platform", category: "platform", projectType: "founder",
    name: { zh: "创作者平台冷启动", en: "Creator platform cold start" },
    description: { zh: "从一种创作者和一个核心价值交换开始验证供需循环。", en: "Validate the supply-demand loop with one creator type and one value exchange." },
    scenario: { zh: "创作者生态", en: "Creator ecosystem" }, scale: { zh: "早期平台", en: "Early-stage platform" },
    title: "创作者平台验证工作区", audience: "连接创作者、内容与受众，仍在寻找初始网络效应的平台团队",
    problem: "团队同时建设创作工具、分发和变现功能，却尚未证明创作者为何持续供给、用户为何持续回来。",
    constraints: "先服务一种创作者；人工运营前 50 名供给者；明确内容治理、版权与退出机制。",
    featureIds: ["problem-framing", "validation-experiments", "onboarding-loop", "asset-pipeline", "community", "membership-billing", "moderation-safety", "analytics-observability"],
    keywords: ["创作者平台", "内容平台", "冷启动", "生态"],
  },
  {
    id: "expert-service-marketplace", category: "platform", projectType: "founder",
    name: { zh: "专家服务撮合平台", en: "Expert service marketplace" },
    description: { zh: "验证专家供给、需求定义、匹配信任与服务评价闭环。", en: "Validate expert supply, demand definition, matching trust, and service review." },
    scenario: { zh: "服务撮合", en: "Service marketplace" }, scale: { zh: "早期平台", en: "Early-stage platform" },
    title: "专家服务平台工作区", audience: "连接顾问、教练、设计师等专业供给与企业或个人需求的平台团队",
    problem: "需求描述不标准、专家质量难判断，平台在尚未理解匹配逻辑前就投入复杂交易功能。",
    constraints: "从一个垂类和人工撮合开始；明确服务边界、退款与争议升级；不替代受监管专业资质审核。",
    featureIds: ["problem-framing", "onboarding-loop", "community", "membership-billing", "role-based-workspaces", "moderation-safety", "privacy-controls", "analytics-observability"],
    keywords: ["专家平台", "撮合", "顾问", "服务市场"],
  },
  {
    id: "association-alumni-community", category: "platform", projectType: "team",
    name: { zh: "协会 / 校友社群运营", en: "Association & alumni community" },
    description: { zh: "围绕成员入会、连接、活动和共同价值建立长期运营节奏。", en: "Build a long-term operating rhythm around onboarding, connections, events, and shared value." },
    scenario: { zh: "成员组织", en: "Member organization" }, scale: { zh: "百人至万人社群", en: "Hundreds to thousands" },
    title: "协会校友社群工作区", audience: "运营行业协会、商会、校友会或专业成员组织的秘书处与志愿团队",
    problem: "成员信息、活动和需求分散，运营只在活动前活跃，无法持续识别成员价值与协作机会。",
    constraints: "成员授权和隐私优先；先服务一个成员分层；明确治理、内容规则与志愿者职责。",
    featureIds: ["onboarding-loop", "community", "role-based-workspaces", "knowledge-base", "moderation-safety", "privacy-controls", "reflection-review", "analytics-observability"],
    keywords: ["协会", "校友会", "商会", "成员运营"],
  },
  {
    id: "coworking-space", category: "local", projectType: "team",
    name: { zh: "联合办公与园区社群", en: "Coworking & campus community" },
    description: { zh: "连接空间服务、企业入驻、活动和成员协作机会。", en: "Connect space services, tenant onboarding, events, and member collaboration." },
    scenario: { zh: "空间社群", en: "Space community" }, scale: { zh: "单点至多园区", en: "Single to multi-site" },
    title: "联合办公园区工作区", audience: "运营联合办公、创业园区或产业社区的空间与社群团队",
    problem: "报修、入驻服务和社群活动各自运行，运营方难以了解企业需求，也无法把空间流量转成真实连接。",
    constraints: "先覆盖一个园区；区分物业请求与社群需求；企业信息经授权使用；每月复盘服务和连接价值。",
    featureIds: ["onboarding-loop", "action-protocol", "community", "role-based-workspaces", "privacy-controls", "offline-localization", "analytics-observability"],
    keywords: ["联合办公", "园区", "孵化器", "空间社群"],
  },
  {
    id: "residential-community-service", category: "local", projectType: "team",
    name: { zh: "社区物业与居民服务", en: "Residential community service" },
    description: { zh: "为居民诉求、公共空间、服务通知和社区改善建立闭环。", en: "Create a loop for resident requests, shared spaces, notices, and community improvement." },
    scenario: { zh: "社区服务", en: "Community service" }, scale: { zh: "单小区至多项目", en: "Single to multi-property" },
    title: "社区物业服务工作区", audience: "服务住宅社区的物业、社区运营和现场服务团队",
    problem: "居民诉求在多个渠道重复出现，处理状态不透明，公共问题和个体问题没有被区分和持续改善。",
    constraints: "保护住户隐私；紧急安全事件走既有应急机制；先覆盖一种服务请求；公开进度不公开个人信息。",
    featureIds: ["onboarding-loop", "action-protocol", "role-based-workspaces", "reflection-review", "privacy-controls", "audit-history", "offline-localization", "analytics-observability"],
    keywords: ["社区", "物业", "居民服务", "报修"],
  },
  {
    id: "eldercare-service", category: "local", projectType: "wellbeing",
    name: { zh: "养老照护服务协同", en: "Eldercare service coordination" },
    description: { zh: "协调非临床照护计划、家属沟通、服务交接与异常升级。", en: "Coordinate non-clinical care plans, family communication, handoffs, and escalation." },
    scenario: { zh: "养老服务", en: "Eldercare services" }, scale: { zh: "居家至机构服务", en: "Home to facility care" },
    title: "养老照护协同工作区", audience: "提供居家养老、日间照料或机构生活照护的服务与运营团队",
    problem: "照护需求、排班交接和家属沟通分散，非临床异常难以及时升级，服务经验依赖个人记忆。",
    constraints: "不用于诊断或治疗；健康与身份信息最小化；明确紧急升级和家属授权；沿用专业照护规范。",
    featureIds: ["onboarding-loop", "action-protocol", "role-based-workspaces", "wellbeing-safety", "privacy-controls", "audit-history", "offline-localization"],
    keywords: ["养老", "照护", "居家服务", "家属沟通"],
  },
  {
    id: "portfolio-pmo", category: "organization", projectType: "team",
    name: { zh: "项目组合与 PMO", en: "Portfolio & PMO" },
    description: { zh: "统一项目优先级、依赖、资源冲突和阶段决策。", en: "Align project priorities, dependencies, resource conflicts, and stage decisions." },
    scenario: { zh: "项目组合治理", en: "Portfolio governance" }, scale: { zh: "中大型组织", en: "Mid-size & enterprise" },
    title: "项目组合 PMO 工作区", audience: "需要同时治理多个战略项目和跨部门依赖的 PMO 与业务负责人",
    problem: "项目各自汇报进度，但共同资源、依赖和停止条件不可见，组织持续增加项目却很少做取舍。",
    constraints: "先纳入一个项目组合；明确继续、调整、暂停门槛；不替代正式投资审批；只保留决策所需粒度。",
    featureIds: ["opportunity-scoring", "decision-journal", "decision-support", "team-operating-system", "role-based-workspaces", "progress-dashboard", "audit-history", "analytics-observability"],
    keywords: ["PMO", "项目组合", "优先级", "资源治理"],
  },
  {
    id: "transformation-change", category: "organization", projectType: "team",
    name: { zh: "组织变革与数字化转型", en: "Transformation & change adoption" },
    description: { zh: "把变革目标、试点、使用反馈和组织学习连接起来。", en: "Connect transformation goals, pilots, adoption feedback, and organizational learning." },
    scenario: { zh: "变革管理", en: "Change management" }, scale: { zh: "中大型组织", en: "Mid-size & enterprise" },
    title: "组织变革转型工作区", audience: "推动流程、系统或组织方式变化的转型办公室、业务负责人和一线代表",
    problem: "项目按计划上线但使用行为未改变，一线阻力被视为沟通问题，真实工作摩擦没有回到方案迭代。",
    constraints: "从一个业务单元和一个行为变化开始；保护反馈者；不把采用率用于简单问责；保留回退方案。",
    featureIds: ["problem-framing", "validation-experiments", "action-protocol", "team-operating-system", "role-based-workspaces", "reflection-review", "analytics-observability"],
    keywords: ["数字化转型", "变革", "采用率", "组织学习"],
  },
  {
    id: "internal-control-audit", category: "organization", projectType: "team",
    name: { zh: "内控整改与审计协同", en: "Internal control & audit remediation" },
    description: { zh: "管理发现事项、整改责任、证据和复核，不替代独立审计判断。", en: "Manage findings, remediation ownership, evidence, and review without replacing independent audit judgment." },
    scenario: { zh: "治理与内控", en: "Governance & controls" }, scale: { zh: "中大型与公共组织", en: "Enterprise & public orgs" },
    title: "内控审计整改工作区", audience: "协调业务、风险、内审和管理层完成控制整改的组织团队",
    problem: "发现事项在报告后分散跟进，整改状态和证据口径不一致，关闭后也缺少有效性复核。",
    constraints: "保持审计独立性；不自动判定关闭；权限分级；每项整改包含责任人、证据、复核人与验证日期。",
    featureIds: ["action-protocol", "role-based-workspaces", "knowledge-base", "privacy-controls", "audit-history", "progress-dashboard", "analytics-observability"],
    keywords: ["内控", "内审", "整改", "审计"],
  },
  {
    id: "solopreneur-studio", category: "personal", projectType: "creator",
    name: { zh: "一人公司经营系统", en: "Solopreneur operating system" },
    description: { zh: "围绕一个客户群管理获客、交付、内容资产和个人精力。", en: "Manage acquisition, delivery, content assets, and energy around one customer group." },
    scenario: { zh: "一人创业", en: "Solopreneurship" }, scale: { zh: "个人经营者", en: "Solo operator" },
    title: "一人公司经营工作区", audience: "独立顾问、自由职业者、创作者或微型服务业务经营者",
    problem: "个人同时承担销售、交付和运营，任务不断切换，缺少明确产品边界和可复用资产，收入依赖持续加时。",
    constraints: "一个细分客户和一个核心服务；每周保留深度交付与资产沉淀时间；不同时启动多个新产品。",
    featureIds: ["problem-framing", "opportunity-scoring", "action-protocol", "asset-pipeline", "portfolio-ledger", "reflection-review", "progress-dashboard"],
    keywords: ["一人公司", "自由职业", "独立顾问", "个人经营"],
  },
  {
    id: "career-transition", category: "personal", projectType: "personal",
    name: { zh: "职业转型与机会验证", en: "Career transition & opportunity validation" },
    description: { zh: "用小实验验证方向、能力差距和真实机会，减少一次性押注。", en: "Use small experiments to validate direction, skill gaps, and real opportunities." },
    scenario: { zh: "职业发展", en: "Career development" }, scale: { zh: "个人", en: "Individual" },
    title: "职业转型工作区", audience: "准备换行业、换职能或从就业转向独立工作的专业人士",
    problem: "用户在多个方向间犹豫，容易依赖想象做重大选择，尚未通过真实任务、访谈和作品验证适配度。",
    constraints: "先做低成本可逆实验；不提供保证性职业结论；每两周依据新证据更新方向与下一步。",
    featureIds: ["problem-framing", "opportunity-scoring", "validation-experiments", "personalized-plans", "learning-studio", "asset-pipeline", "reflection-review"],
    keywords: ["职业转型", "转行", "求职", "机会验证"],
  },
  {
    id: "expert-ip-commercialization", category: "personal", projectType: "creator",
    name: { zh: "专家个人品牌与 IP 商业化", en: "Expert brand & IP commercialization" },
    description: { zh: "把专业积累转为可信内容、服务产品和长期知识资产。", en: "Turn expertise into trusted content, service products, and durable knowledge assets." },
    scenario: { zh: "专家品牌", en: "Expert brand" }, scale: { zh: "个人至小团队", en: "Individual to small team" },
    title: "专家 IP 商业化工作区", audience: "希望建立专业影响力并发展咨询、课程或内容产品的资深从业者",
    problem: "专业经验丰富却表达分散，内容与业务没有共同主题，商业化容易损害专业可信度或形成过度承诺。",
    constraints: "只围绕一个专业问题；事实、经验与观点分开表达；先验证服务结果，再扩展内容和产品矩阵。",
    featureIds: ["problem-framing", "knowledge-base", "asset-pipeline", "portfolio-ledger", "validation-experiments", "membership-billing", "analytics-observability"],
    keywords: ["个人品牌", "专家IP", "商业化", "专业内容"],
  },
  {
    id: "employee-wellbeing", category: "care", projectType: "wellbeing",
    name: { zh: "员工身心健康支持", en: "Employee wellbeing support" },
    description: { zh: "提供非诊断式自助资源、求助入口和匿名趋势反馈。", en: "Offer non-diagnostic self-help resources, support access, and anonymous trend feedback." },
    scenario: { zh: "员工关怀", en: "Employee care" }, scale: { zh: "中大型组织", en: "Mid-size & enterprise" },
    title: "员工身心支持工作区", audience: "希望为员工提供日常压力支持和清晰求助路径的人力与员工关怀团队",
    problem: "员工不知道何时、如何寻求支持，组织只能看到滞后的离职或缺勤信号，同时个体隐私和管理边界容易混淆。",
    constraints: "不诊断、不向经理暴露个人内容；匿名汇总需满足最小群体阈值；危机情况明确连接当地专业与紧急资源。",
    featureIds: ["onboarding-loop", "habit-practice", "reflection-review", "wellbeing-safety", "moderation-safety", "privacy-controls", "analytics-observability"],
    keywords: ["员工关怀", "EAP", "压力", "心理安全"],
  },
  {
    id: "family-caregiver-support", category: "care", projectType: "wellbeing",
    name: { zh: "家庭照护者支持", en: "Family caregiver support" },
    description: { zh: "帮助长期照护者管理自身节奏、求助资源和家庭协作。", en: "Help long-term caregivers manage their own rhythm, support resources, and family coordination." },
    scenario: { zh: "照护者支持", en: "Caregiver support" }, scale: { zh: "个人与家庭", en: "Individuals & families" },
    title: "家庭照护者支持工作区", audience: "长期照护老人、慢性病家人或特殊需要家庭成员的非专业照护者",
    problem: "照护者长期高负荷却忽略自身状态，家庭分工和求助信息不清，压力上升时缺少简单、可信的支持路径。",
    constraints: "不提供医疗建议或替代专业照护；保护被照护者隐私；紧急情况使用当地医疗与应急资源。",
    featureIds: ["onboarding-loop", "habit-practice", "reflection-review", "ai-coach", "wellbeing-safety", "privacy-controls", "family-space"],
    keywords: ["照护者", "家庭照护", "老人", "支持"],
  },
  {
    id: "youth-wellbeing-support", category: "care", projectType: "family",
    name: { zh: "青少年成长支持", en: "Youth wellbeing support" },
    description: { zh: "以适龄、非诊断方式支持情绪表达、家庭沟通和求助。", en: "Support age-appropriate emotional expression, family communication, and help-seeking without diagnosis." },
    scenario: { zh: "青少年支持", en: "Youth support" }, scale: { zh: "家庭与教育支持", en: "Family & education support" },
    title: "青少年成长支持工作区", audience: "希望建立低压力沟通、日常调节和求助机制的家庭与支持人员",
    problem: "青少年不愿在被评判的环境中表达，家长容易把记录变成监控，真正需要专业帮助时又缺少明确升级路径。",
    constraints: "监护与青少年隐私边界清晰；不诊断、不排名；高风险信号立即转介专业人员和当地紧急资源。",
    featureIds: ["family-space", "habit-practice", "reflection-review", "wellbeing-safety", "moderation-safety", "privacy-controls", "audit-history"],
    keywords: ["青少年", "家庭沟通", "情绪支持", "成长"],
  },
];
