"use client";

// Surfaces the latest weekly growth card on the dashboard (the "push": it appears
// on landing). Auto-generated by the weekly job; can be generated/refreshed here.

import { useState } from "react";
import { Card } from "@/components/ui";
import { useApi, useApiMutation } from "@/lib/hooks";
import { useI18n, useT } from "@/lib/i18n/client";
import ShareCardModal from "@/components/ShareCardModal";

interface WeeklyCard { headline: string; lines: string[]; score: number; generatedAt: number }

export default function WeeklyCardBanner() {
  const { locale } = useI18n();
  const T = useT();
  const q = useApi<{ latest: WeeklyCard | null }>("/api/growth-card");
  const gen = useApiMutation<undefined, { card: WeeklyCard }>("/api/growth-card", { invalidate: ["/api/growth-card"] });
  const [share, setShare] = useState(false);
  const card = gen.data?.card ?? q.data?.latest ?? null;

  return (
    <Card title={T("本周成长卡片", "This week's growth card")}>
      {card ? (
        <div>
          <div className="text-sm font-medium text-slate-100">{card.headline}</div>
          <ul className="mt-1 flex flex-wrap gap-x-4 gap-y-0.5 text-xs text-slate-400">
            {card.lines.map((l, i) => <li key={i}>· {l}</li>)}
          </ul>
          <div className="mt-2 flex gap-2">
            <button onClick={() => setShare(true)} className="rounded-lg bg-amber-500 px-3 py-1.5 text-xs font-semibold text-slate-900 hover:bg-amber-400">{T("🪪 分享卡片", "🪪 Share card")}</button>
            <button onClick={() => gen.mutate(undefined)} disabled={gen.isPending} className="rounded-lg border border-slate-700 px-3 py-1.5 text-xs text-slate-300 hover:bg-slate-800 disabled:opacity-50">{gen.isPending ? "…" : T("刷新", "Refresh")}</button>
          </div>
        </div>
      ) : (
        <div className="flex items-center justify-between gap-3">
          <p className="text-sm text-slate-400">{T("还没有本周卡片(每周一自动生成)。", "No card yet — auto-generated every Monday.")}</p>
          <button onClick={() => gen.mutate(undefined)} disabled={gen.isPending} className="rounded-lg bg-indigo-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-indigo-500 disabled:opacity-50">{gen.isPending ? "…" : T("立即生成", "Generate now")}</button>
        </div>
      )}
      {share && card && (
        <ShareCardModal title={T("我的成长 OS", "My Growth OS")} content={card.lines.join("\n")} source={`score ${card.score}`} onClose={() => setShare(false)} />
      )}
    </Card>
  );
}
